version: '3'

services:
  publication_db:
    image: postgres:16
    container_name: publication_db
    volumes:
      - publication_data_16:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=publication_db
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test

  subscription_db:
    image: postgres:16
    container_name: subscription_db
    volumes:
      - subscription_data_16:/var/lib/postgresql/data/
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=subscription_db
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test

volumes:
  publication_data_16:
  subscription_data_16: